// NSE/BSE stocks dataset — Yahoo Finance ticker (.NS = NSE, .BO = BSE)
// All values in INR. This is the client-side search corpus.
export interface IndianStock {
  symbol: string   // Yahoo ticker e.g. RELIANCE.NS
  name:   string   // Full company name
  sector: string
  exchange: 'NSE' | 'BSE'
}

const NSE: IndianStock[] = [
  // Nifty 50
  { symbol:'RELIANCE.NS',    name:'Reliance Industries',           sector:'Energy',          exchange:'NSE' },
  { symbol:'TCS.NS',         name:'Tata Consultancy Services',     sector:'IT',              exchange:'NSE' },
  { symbol:'HDFCBANK.NS',    name:'HDFC Bank',                     sector:'Banking',         exchange:'NSE' },
  { symbol:'BHARTIARTL.NS',  name:'Bharti Airtel',                 sector:'Telecom',         exchange:'NSE' },
  { symbol:'ICICIBANK.NS',   name:'ICICI Bank',                    sector:'Banking',         exchange:'NSE' },
  { symbol:'INFOSYS.NS',     name:'Infosys',                       sector:'IT',              exchange:'NSE' },
  { symbol:'INFY.NS',        name:'Infosys (Alt)',                  sector:'IT',              exchange:'NSE' },
  { symbol:'SBIN.NS',        name:'State Bank of India',           sector:'Banking',         exchange:'NSE' },
  { symbol:'ITC.NS',         name:'ITC',                           sector:'FMCG',            exchange:'NSE' },
  { symbol:'LT.NS',          name:'Larsen & Toubro',               sector:'Industrials',     exchange:'NSE' },
  { symbol:'HINDUNILVR.NS',  name:'Hindustan Unilever',            sector:'FMCG',            exchange:'NSE' },
  { symbol:'BAJFINANCE.NS',  name:'Bajaj Finance',                 sector:'Finance',         exchange:'NSE' },
  { symbol:'KOTAKBANK.NS',   name:'Kotak Mahindra Bank',           sector:'Banking',         exchange:'NSE' },
  { symbol:'HCLTECH.NS',     name:'HCL Technologies',              sector:'IT',              exchange:'NSE' },
  { symbol:'ASIANPAINT.NS',  name:'Asian Paints',                  sector:'Consumer',        exchange:'NSE' },
  { symbol:'AXISBANK.NS',    name:'Axis Bank',                     sector:'Banking',         exchange:'NSE' },
  { symbol:'MARUTI.NS',      name:'Maruti Suzuki India',           sector:'Auto',            exchange:'NSE' },
  { symbol:'SUNPHARMA.NS',   name:'Sun Pharmaceutical',            sector:'Pharma',          exchange:'NSE' },
  { symbol:'TITAN.NS',       name:'Titan Company',                 sector:'Consumer',        exchange:'NSE' },
  { symbol:'WIPRO.NS',       name:'Wipro',                         sector:'IT',              exchange:'NSE' },
  { symbol:'ULTRACEMCO.NS',  name:'UltraTech Cement',              sector:'Materials',       exchange:'NSE' },
  { symbol:'TECHM.NS',       name:'Tech Mahindra',                 sector:'IT',              exchange:'NSE' },
  { symbol:'NTPC.NS',        name:'NTPC',                          sector:'Utilities',       exchange:'NSE' },
  { symbol:'POWERGRID.NS',   name:'Power Grid Corporation',        sector:'Utilities',       exchange:'NSE' },
  { symbol:'ONGC.NS',        name:'Oil & Natural Gas Corporation', sector:'Energy',          exchange:'NSE' },
  { symbol:'BAJAJFINSV.NS',  name:'Bajaj Finserv',                 sector:'Finance',         exchange:'NSE' },
  { symbol:'M&M.NS',         name:'Mahindra & Mahindra',           sector:'Auto',            exchange:'NSE' },
  { symbol:'TATAMOTORS.NS',  name:'Tata Motors',                   sector:'Auto',            exchange:'NSE' },
  { symbol:'TATASTEEL.NS',   name:'Tata Steel',                    sector:'Materials',       exchange:'NSE' },
  { symbol:'ADANIENT.NS',    name:'Adani Enterprises',             sector:'Industrials',     exchange:'NSE' },
  { symbol:'ADANIPORTS.NS',  name:'Adani Ports',                   sector:'Industrials',     exchange:'NSE' },
  { symbol:'ADANIGREEN.NS',  name:'Adani Green Energy',            sector:'Energy',          exchange:'NSE' },
  { symbol:'COALINDIA.NS',   name:'Coal India',                    sector:'Materials',       exchange:'NSE' },
  { symbol:'HINDALCO.NS',    name:'Hindalco Industries',           sector:'Materials',       exchange:'NSE' },
  { symbol:'JSWSTEEL.NS',    name:'JSW Steel',                     sector:'Materials',       exchange:'NSE' },
  { symbol:'EICHERMOT.NS',   name:'Eicher Motors',                 sector:'Auto',            exchange:'NSE' },
  { symbol:'HEROMOTOCO.NS',  name:'Hero MotoCorp',                 sector:'Auto',            exchange:'NSE' },
  { symbol:'INDUSINDBK.NS',  name:'IndusInd Bank',                 sector:'Banking',         exchange:'NSE' },
  { symbol:'CIPLA.NS',       name:'Cipla',                         sector:'Pharma',          exchange:'NSE' },
  { symbol:'DRREDDY.NS',     name:'Dr Reddy\'s Laboratories',      sector:'Pharma',          exchange:'NSE' },
  { symbol:'NESTLEIND.NS',   name:'Nestle India',                  sector:'FMCG',            exchange:'NSE' },
  { symbol:'BRITANNIA.NS',   name:'Britannia Industries',          sector:'FMCG',            exchange:'NSE' },
  { symbol:'DIVISLAB.NS',    name:'Divi\'s Laboratories',          sector:'Pharma',          exchange:'NSE' },
  { symbol:'APOLLOHOSP.NS',  name:'Apollo Hospitals',              sector:'Healthcare',      exchange:'NSE' },
  { symbol:'BPCL.NS',        name:'Bharat Petroleum',              sector:'Energy',          exchange:'NSE' },
  { symbol:'GRASIM.NS',      name:'Grasim Industries',             sector:'Materials',       exchange:'NSE' },
  { symbol:'TATACONSUM.NS',  name:'Tata Consumer Products',        sector:'FMCG',            exchange:'NSE' },
  { symbol:'SBILIFE.NS',     name:'SBI Life Insurance',            sector:'Insurance',       exchange:'NSE' },
  { symbol:'HDFCLIFE.NS',    name:'HDFC Life Insurance',           sector:'Insurance',       exchange:'NSE' },
  { symbol:'LTF.NS',         name:'L&T Finance',                   sector:'Finance',         exchange:'NSE' },

  // Nifty Next 50 & popular mid-caps
  { symbol:'PIDILITIND.NS',  name:'Pidilite Industries',           sector:'Materials',       exchange:'NSE' },
  { symbol:'SIEMENS.NS',     name:'Siemens India',                 sector:'Industrials',     exchange:'NSE' },
  { symbol:'HAVELLS.NS',     name:'Havells India',                 sector:'Consumer',        exchange:'NSE' },
  { symbol:'MARICO.NS',      name:'Marico',                        sector:'FMCG',            exchange:'NSE' },
  { symbol:'DABUR.NS',       name:'Dabur India',                   sector:'FMCG',            exchange:'NSE' },
  { symbol:'GODREJCP.NS',    name:'Godrej Consumer Products',      sector:'FMCG',            exchange:'NSE' },
  { symbol:'COLPAL.NS',      name:'Colgate-Palmolive India',       sector:'FMCG',            exchange:'NSE' },
  { symbol:'EMAMILTD.NS',    name:'Emami',                         sector:'FMCG',            exchange:'NSE' },
  { symbol:'BERGEPAINT.NS',  name:'Berger Paints',                 sector:'Materials',       exchange:'NSE' },
  { symbol:'MCDOWELL-N.NS',  name:'United Spirits',                sector:'Consumer',        exchange:'NSE' },
  { symbol:'UBL.NS',         name:'United Breweries',              sector:'Consumer',        exchange:'NSE' },
  { symbol:'TRENT.NS',       name:'Trent',                         sector:'Retail',          exchange:'NSE' },
  { symbol:'NYKAA.NS',       name:'FSN E-Commerce (Nykaa)',        sector:'Retail',          exchange:'NSE' },
  { symbol:'ZOMATO.NS',      name:'Zomato',                        sector:'Consumer Tech',   exchange:'NSE' },
  { symbol:'PAYTM.NS',       name:'Paytm (One 97 Comm)',           sector:'Fintech',         exchange:'NSE' },
  { symbol:'POLICYBZR.NS',   name:'PB Fintech (PolicyBazaar)',     sector:'Fintech',         exchange:'NSE' },
  { symbol:'IRCTC.NS',       name:'IRCTC',                         sector:'Travel & Tourism',exchange:'NSE' },
  { symbol:'DMART.NS',       name:'Avenue Supermarts (DMart)',     sector:'Retail',          exchange:'NSE' },
  { symbol:'PAGEIND.NS',     name:'Page Industries',               sector:'Consumer',        exchange:'NSE' },
  { symbol:'MUTHOOTFIN.NS',  name:'Muthoot Finance',               sector:'Finance',         exchange:'NSE' },
  { symbol:'CHOLAFIN.NS',    name:'Cholamandalam Investment',      sector:'Finance',         exchange:'NSE' },
  { symbol:'LICHSGFIN.NS',   name:'LIC Housing Finance',           sector:'Finance',         exchange:'NSE' },
  { symbol:'BANKBARODA.NS',  name:'Bank of Baroda',                sector:'Banking',         exchange:'NSE' },
  { symbol:'PNB.NS',         name:'Punjab National Bank',          sector:'Banking',         exchange:'NSE' },
  { symbol:'CANBK.NS',       name:'Canara Bank',                   sector:'Banking',         exchange:'NSE' },
  { symbol:'FEDERALBNK.NS',  name:'Federal Bank',                  sector:'Banking',         exchange:'NSE' },
  { symbol:'IDFCFIRSTB.NS',  name:'IDFC First Bank',               sector:'Banking',         exchange:'NSE' },
  { symbol:'RBLBANK.NS',     name:'RBL Bank',                      sector:'Banking',         exchange:'NSE' },
  { symbol:'ICICIGI.NS',     name:'ICICI Lombard',                 sector:'Insurance',       exchange:'NSE' },
  { symbol:'STARHEALTH.NS',  name:'Star Health Insurance',         sector:'Insurance',       exchange:'NSE' },
  { symbol:'BAJAJ-AUTO.NS',  name:'Bajaj Auto',                    sector:'Auto',            exchange:'NSE' },
  { symbol:'ASHOKLEY.NS',    name:'Ashok Leyland',                 sector:'Auto',            exchange:'NSE' },
  { symbol:'EXIDEIND.NS',    name:'Exide Industries',              sector:'Auto',            exchange:'NSE' },
  { symbol:'BOSCHLTD.NS',    name:'Bosch',                         sector:'Auto',            exchange:'NSE' },
  { symbol:'TVSMOTOR.NS',    name:'TVS Motor Company',             sector:'Auto',            exchange:'NSE' },
  { symbol:'ESCORTS.NS',     name:'Escorts Kubota',                sector:'Industrials',     exchange:'NSE' },
  { symbol:'HAL.NS',         name:'Hindustan Aeronautics',         sector:'Defence',         exchange:'NSE' },
  { symbol:'BEL.NS',         name:'Bharat Electronics',            sector:'Defence',         exchange:'NSE' },
  { symbol:'HINDPETRO.NS',   name:'Hindustan Petroleum',           sector:'Energy',          exchange:'NSE' },
  { symbol:'IOC.NS',         name:'Indian Oil Corporation',        sector:'Energy',          exchange:'NSE' },
  { symbol:'GAIL.NS',        name:'GAIL India',                    sector:'Energy',          exchange:'NSE' },
  { symbol:'PETRONET.NS',    name:'Petronet LNG',                  sector:'Energy',          exchange:'NSE' },
  { symbol:'NHPC.NS',        name:'NHPC',                          sector:'Utilities',       exchange:'NSE' },
  { symbol:'SJVN.NS',        name:'SJVN',                          sector:'Utilities',       exchange:'NSE' },
  { symbol:'RECLTD.NS',      name:'REC',                           sector:'Finance',         exchange:'NSE' },
  { symbol:'PFC.NS',         name:'Power Finance Corporation',     sector:'Finance',         exchange:'NSE' },
  { symbol:'IRFC.NS',        name:'Indian Railway Finance Corp',   sector:'Finance',         exchange:'NSE' },
  { symbol:'LUPIN.NS',       name:'Lupin',                         sector:'Pharma',          exchange:'NSE' },
  { symbol:'AUROPHARMA.NS',  name:'Aurobindo Pharma',              sector:'Pharma',          exchange:'NSE' },
  { symbol:'TORNTPHARM.NS',  name:'Torrent Pharmaceuticals',       sector:'Pharma',          exchange:'NSE' },
  { symbol:'ALKEM.NS',       name:'Alkem Laboratories',            sector:'Pharma',          exchange:'NSE' },
  { symbol:'ABBOTINDIA.NS',  name:'Abbott India',                  sector:'Pharma',          exchange:'NSE' },
  { symbol:'PFIZER.NS',      name:'Pfizer India',                  sector:'Pharma',          exchange:'NSE' },
  { symbol:'MAXHEALTH.NS',   name:'Max Healthcare',                sector:'Healthcare',      exchange:'NSE' },
  { symbol:'FORTIS.NS',      name:'Fortis Healthcare',             sector:'Healthcare',      exchange:'NSE' },
  { symbol:'KPITTECH.NS',    name:'KPIT Technologies',             sector:'IT',              exchange:'NSE' },
  { symbol:'LTTS.NS',        name:'L&T Technology Services',       sector:'IT',              exchange:'NSE' },
  { symbol:'MPHASIS.NS',     name:'Mphasis',                       sector:'IT',              exchange:'NSE' },
  { symbol:'COFORGE.NS',     name:'Coforge',                       sector:'IT',              exchange:'NSE' },
  { symbol:'PERSISTENT.NS',  name:'Persistent Systems',            sector:'IT',              exchange:'NSE' },
  { symbol:'OFSS.NS',        name:'Oracle Financial Services',     sector:'IT',              exchange:'NSE' },
  { symbol:'INFOEDGE.NS',    name:'Info Edge (Naukri)',            sector:'Consumer Tech',   exchange:'NSE' },
  { symbol:'INDIAMART.NS',   name:'IndiaMART InterMESH',           sector:'Consumer Tech',   exchange:'NSE' },
  { symbol:'JUSTDIAL.NS',    name:'Just Dial',                     sector:'Consumer Tech',   exchange:'NSE' },
  { symbol:'DIXON.NS',       name:'Dixon Technologies',            sector:'Electronics',     exchange:'NSE' },
  { symbol:'KAYNES.NS',      name:'Kaynes Technology',             sector:'Electronics',     exchange:'NSE' },
  { symbol:'AMBER.NS',       name:'Amber Enterprises',             sector:'Electronics',     exchange:'NSE' },
  { symbol:'POLYCAB.NS',     name:'Polycab India',                 sector:'Industrials',     exchange:'NSE' },
  { symbol:'KFINTECH.NS',    name:'KFin Technologies',             sector:'Fintech',         exchange:'NSE' },

  // Popular ETFs
  { symbol:'NIFTYBEES.NS',   name:'Nippon Nifty BeES ETF',         sector:'ETF – Nifty 50', exchange:'NSE' },
  { symbol:'JUNIORBEES.NS',  name:'Nippon Junior BeES ETF',        sector:'ETF – Nifty Jr',  exchange:'NSE' },
  { symbol:'BANKBEES.NS',    name:'Nippon Bank BeES ETF',          sector:'ETF – Banking',   exchange:'NSE' },
  { symbol:'GOLDBEES.NS',    name:'Nippon Gold BeES ETF',          sector:'ETF – Gold',      exchange:'NSE' },
  { symbol:'ICICIB22.NS',    name:'ICICI Pru Nifty Next 50 ETF',   sector:'ETF',             exchange:'NSE' },
  { symbol:'MOM100.NS',      name:'Mirae Nifty 100 Momentum ETF',  sector:'ETF',             exchange:'NSE' },
  { symbol:'SETFNN50.NS',    name:'SBI Nifty Next 50 ETF',         sector:'ETF',             exchange:'NSE' },
  { symbol:'ITBEES.NS',      name:'Nippon IT BeES ETF',            sector:'ETF – IT',        exchange:'NSE' },
]

export default NSE
